Vue.component('button-loading', require('./button-loading'));
Vue.component('button-dropdown', require('./button-dropdown'));
Vue.component('input-text', require('./input-text'));
Vue.component('modal', require('./modal'));
Vue.component('pagination', require('./pagination'));
Vue.component('editable', require('./editable'));
Vue.component('divisor', require('./divisor'));
Vue.component('save-indicator', require('./save-indicator'));
Vue.component('input-textarea', require('./input-textarea'));
